INSERT INTO cars_details (car_id, detail_id) VALUES (1, 9);
INSERT INTO cars_details (car_id, detail_id) VALUES (1, 8);
INSERT INTO cars_details (car_id, detail_id) VALUES (2, 7);
INSERT INTO cars_details (car_id, detail_id) VALUES (2, 6);
INSERT INTO cars_details (car_id, detail_id) VALUES (3, 5);
INSERT INTO cars_details (car_id, detail_id) VALUES (3, 4);
INSERT INTO cars_details (car_id, detail_id) VALUES (4, 3);
INSERT INTO cars_details (car_id, detail_id) VALUES (4, 2);
INSERT INTO cars_details (car_id, detail_id) VALUES (5, 1);